changelog:
  categories:
    - title: ✨ Implemented enhancements
      labels: 
        - enhancement
    - title: 🐛 Fixed bugs
      labels: 
        - bug        
    - title: 📝 Documentation updates
      labels: 
        - docs
    - title: 🔨 Other
      labels: 
        - '*'
      exclude:
        labels:
          - dependencies